// Mocks generated by Mockito 5.4.0 from annotations
// in recipes/test/app/features/home/presentation/controllers/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:recipes/app/features/home/domain/entities/ingredients_entity.dart'
    as _i10;
import 'package:recipes/app/features/home/domain/entities/recipe_entity.dart'
    as _i7;
import 'package:recipes/app/features/home/domain/repositories/home_repositories.dart'
    as _i2;
import 'package:recipes/app/features/home/domain/usecases/fetch_ingredients_usecase.dart'
    as _i9;
import 'package:recipes/app/features/home/domain/usecases/fetch_recipes_usecase.dart'
    as _i4;
import 'package:recipes/core/error/failures.dart' as _i6;
import 'package:recipes/core/parameters/fetch_recipe_params.dart' as _i8;
import 'package:recipes/core/parameters/no_params.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeRepository_0 extends _i1.SmartFake
    implements _i2.HomeRepository {
  _FakeHomeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchRecipesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchRecipesUsecase extends _i1.Mock
    implements _i4.FetchRecipesUsecase {
  MockFetchRecipesUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HomeRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.RecipeEntity>>> call(
          _i8.FetchRecipeParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.RecipeEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.RecipeEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.RecipeEntity>>>);
}

/// A class which mocks [FetchIngredientsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchIngredientsUsecase extends _i1.Mock
    implements _i9.FetchIngredientsUsecase {
  MockFetchIngredientsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HomeRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i10.IngredientEntity>>> call(
          _i11.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, List<_i10.IngredientEntity>>>.value(
            _FakeEither_1<_i6.Failure, List<_i10.IngredientEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i10.IngredientEntity>>>);
}
