part of './app_pages.dart';

abstract class Routes {
  static const initial = '/';
  static const home = '/home';
  static const details = '/details';
  static const roles = '/roles';
  static const deals = '/deals';
  static const favouritedeals = '/deals/favourites';
  static const notification = '/notification';
  static const searchLocation = '/location';
  static const account = '/account';
  static const uploadProfileImage = '/account/profile/update';
  static const businessInfo = '/business-info';
  static const notificationSettings = '/settings/notification';
  static const preferences = '/settings/preferences';
  static const accountSettings = '/settings/account';
  static const help = '/help';
  static const payments = '/payments';
  static const paymentPlans = '/payments/plans';
  static const shareApp = '/share-app';
  static const changePassword = '/password/change';
  static const dealDetails = '/deals/details';
  static const onboarding = '/onboarding';
  static const notificationSetup = '/notification-setup';
  static const signup = '/signup';
  static const verifycode = '/verification';
  static const signin = '/signin';
  static const reviewDeal = '/review';
  static const dealsDirection = '/deals/directions';
  static const filterSearch = '/deals/filter';
  static const publishDeal = '/deals/create/image';
  static const addDealInfo = '/deals/create/info';
  static const addDealOptions = '/deals/create/options';
  static const resetPassword = '/reset-password';
  static const resetPasswordCodeVerify = '/verify-code';
  static const resetPasswordUserDetails = '/reset-password/data';
  static const userOnboardingSetup = '/account/setup';
  static const locationOnMap = '/account/setup/location/map';
  static const searchDeals = '/deals/search';
  static const sellerProfile = '/profile';
}
