// Mocks generated by Mockito 5.4.0 from annotations
// in recipes/test/app/features/home/domain/usecases/fetch_recipes_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:recipes/app/features/home/domain/entities/ingredients_entity.dart'
    as _i8;
import 'package:recipes/app/features/home/domain/entities/recipe_entity.dart'
    as _i6;
import 'package:recipes/app/features/home/domain/repositories/home_repositories.dart'
    as _i3;
import 'package:recipes/core/error/failures.dart' as _i5;
import 'package:recipes/core/parameters/fetch_recipe_params.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i3.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.RecipeEntity>>> fetchRecipes(
          {required _i7.FetchRecipeParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRecipes,
          [],
          {#params: params},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.RecipeEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.RecipeEntity>>(
          this,
          Invocation.method(
            #fetchRecipes,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.RecipeEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.IngredientEntity>>>
      fetchIngredients() => (super.noSuchMethod(
            Invocation.method(
              #fetchIngredients,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i8.IngredientEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.IngredientEntity>>(
              this,
              Invocation.method(
                #fetchIngredients,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.IngredientEntity>>>);
}
